# Generated by Django 6.0.7 on 2026-08-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_updated_at_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
