# Generated by Django 6.0.7 on 2026-08-07 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_appointment_id'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='appointments.appointment'),
            preserve_default=False,
        ),
    ]
