# Generated by Django 6.0.7 on 2026-07-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_admin_created_at_remove_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
